apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devopsdep
  name: devopsdep
  namespace: devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devopsdep
  template:
    metadata:
      labels:
        app: devopsdep
    spec:
      containers:
        - image: king950/devopspython:023a2c61bf00dd7988f9f03d4e466862f5ed85ee
          name: devopspython
