apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devopsdep
  name: devopsdep
  namespace: devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devopsdep
  template:
    metadata:
      labels:
        app: devopsdep
    spec:
      containers:
        - image: king950/devopspython:d180ad5366944b2b6c76572631d272f60c95aa11
          name: devopspython
