apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devopsdep
  name: devopsdep
  namespace: devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devopsdep
  template:
    metadata:
      labels:
        app: devopsdep
    spec:
      containers:
        - image: king950/devopspython:900362c83a94bf670e7db1cd0d705c4c23f9a01a
          name: devopspython
